USE PrecoCarros;

SELECT 
	FORMAT(AVG(TRY_CONVERT(DECIMAL(10,2),Price)),'C', 'PT-BR') AS [PRECO MEDIO],
	FORMAT(MAX(TRY_CONVERT(DECIMAL(10,2), Price)),'C','PT-BR') AS [PRECO MAXIMO],
	FORMAT(MIN(TRY_CONVERT(DECIMAL(10,2),Price)),'C', 'PT-BR') AS [PRECO MINIMO]
FROM car_price_prediction_;